// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKLUT9q1tJL56Hy8kiR-aCAKPpVTM7uY',
    appId: '1:248049763918:web:3cc0ab3ada5fa83711e51f',
    messagingSenderId: '248049763918',
    projectId: 'forum-8f3cc',
    authDomain: 'forum-8f3cc.firebaseapp.com',
    storageBucket: 'forum-8f3cc.firebasestorage.app',
    measurementId: 'G-65YEJGVXM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeFqm2d4sZpikFkFPlcy0Iw6CfGSk93Tc',
    appId: '1:248049763918:android:ce6d74b09b1cd67211e51f',
    messagingSenderId: '248049763918',
    projectId: 'forum-8f3cc',
    storageBucket: 'forum-8f3cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2hnhzgjSH9GUKzPos7TJQfZumkLDGqdI',
    appId: '1:248049763918:ios:756965523575365d11e51f',
    messagingSenderId: '248049763918',
    projectId: 'forum-8f3cc',
    storageBucket: 'forum-8f3cc.firebasestorage.app',
    iosBundleId: 'com.example.newspaperAppTheForum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2hnhzgjSH9GUKzPos7TJQfZumkLDGqdI',
    appId: '1:248049763918:ios:756965523575365d11e51f',
    messagingSenderId: '248049763918',
    projectId: 'forum-8f3cc',
    storageBucket: 'forum-8f3cc.firebasestorage.app',
    iosBundleId: 'com.example.newspaperAppTheForum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzKLUT9q1tJL56Hy8kiR-aCAKPpVTM7uY',
    appId: '1:248049763918:web:e440e52b249b45ee11e51f',
    messagingSenderId: '248049763918',
    projectId: 'forum-8f3cc',
    authDomain: 'forum-8f3cc.firebaseapp.com',
    storageBucket: 'forum-8f3cc.firebasestorage.app',
    measurementId: 'G-40SSJT1PB1',
  );
}
